Act_name=(
    'SonicTheHedgehog-Genesis SpringYardZone.Act3'
    'SonicTheHedgehog-Genesis SpringYardZone.Act2'
    'SonicTheHedgehog-Genesis GreenHillZone.Act3'
    'SonicTheHedgehog-Genesis GreenHillZone.Act1'
    'SonicTheHedgehog-Genesis StarLightZone.Act2'
    'SonicTheHedgehog-Genesis StarLightZone.Act1'
    'SonicTheHedgehog-Genesis MarbleZone.Act2'
    'SonicTheHedgehog-Genesis MarbleZone.Act1'
    'SonicTheHedgehog-Genesis MarbleZone.Act3'
    'SonicTheHedgehog-Genesis ScrapBrainZone.Act2'
    'SonicTheHedgehog-Genesis LabyrinthZone.Act2'
    'SonicTheHedgehog-Genesis LabyrinthZone.Act1'
    'SonicTheHedgehog-Genesis LabyrinthZone.Act3'
    'SonicTheHedgehog2-Genesis EmeraldHillZone.Act1'
    'SonicTheHedgehog2-Genesis EmeraldHillZone.Act2'
    'SonicTheHedgehog2-Genesis ChemicalPlantZone.Act2'
    'SonicTheHedgehog2-Genesis ChemicalPlantZone.Act1'
    'SonicTheHedgehog2-Genesis MetropolisZone.Act1'
    'SonicTheHedgehog2-Genesis MetropolisZone.Act2'
    'SonicTheHedgehog2-Genesis OilOceanZone.Act1'
    'SonicTheHedgehog2-Genesis OilOceanZone.Act2'
    'SonicTheHedgehog2-Genesis MysticCaveZone.Act2'
    'SonicTheHedgehog2-Genesis MysticCaveZone.Act1'
    'SonicTheHedgehog2-Genesis HillTopZone.Act1'
    'SonicTheHedgehog2-Genesis CasinoNightZone.Act1'
    'SonicTheHedgehog2-Genesis WingFortressZone'
    'SonicTheHedgehog2-Genesis AquaticRuinZone.Act2'
    'SonicTheHedgehog2-Genesis AquaticRuinZone.Act1'
    'SonicAndKnuckles3-Genesis LavaReefZone.Act2'
    'SonicAndKnuckles3-Genesis CarnivalNightZone.Act2'
    'SonicAndKnuckles3-Genesis CarnivalNightZone.Act1'
    'SonicAndKnuckles3-Genesis MarbleGardenZone.Act1'
    'SonicAndKnuckles3-Genesis MarbleGardenZone.Act2'
    'SonicAndKnuckles3-Genesis MushroomHillZone.Act2'
    'SonicAndKnuckles3-Genesis MushroomHillZone.Act1'
    'SonicAndKnuckles3-Genesis DeathEggZone.Act1'
    'SonicAndKnuckles3-Genesis DeathEggZone.Act2'
    'SonicAndKnuckles3-Genesis FlyingBatteryZone.Act1'
    'SonicAndKnuckles3-Genesis SandopolisZone.Act1'
    'SonicAndKnuckles3-Genesis SandopolisZone.Act2'
    'SonicAndKnuckles3-Genesis HiddenPalaceZone'
    'SonicAndKnuckles3-Genesis HydrocityZone.Act2'
    'SonicAndKnuckles3-Genesis IcecapZone.Act1'
    'SonicAndKnuckles3-Genesis IcecapZone.Act2'
    'SonicAndKnuckles3-Genesis AngelIslandZone.Act1'
    'SonicAndKnuckles3-Genesis LaunchBaseZone.Act2'
    'SonicAndKnuckles3-Genesis LaunchBaseZone.Act1'
    'SonicTheHedgehog-Genesis SpringYardZone.Act1'
    'SonicTheHedgehog-Genesis GreenHillZone.Act2'
    'SonicTheHedgehog-Genesis StarLightZone.Act3'
    'SonicTheHedgehog-Genesis ScrapBrainZone.Act1'
    'SonicTheHedgehog2-Genesis MetropolisZone.Act3'
    'SonicTheHedgehog2-Genesis HillTopZone.Act2'
    'SonicTheHedgehog2-Genesis CasinoNightZone.Act2'
    'SonicAndKnuckles3-Genesis LavaReefZone.Act1'
    'SonicAndKnuckles3-Genesis FlyingBatteryZone.Act2'
    'SonicAndKnuckles3-Genesis HydrocityZone.Act1'
    'SonicAndKnuckles3-Genesis AngelIslandZone.Act2'
)

results=(
    'all2_sy3'
    'all2_sy2'
    'all2_gh3'
    'all2_gh1'
    'all2_sl2'
    'all2_sl1'
    'all2_mz2'
    'all2_mz1'
    'all2_mz3'
    'all2_sb2'
    'all2_lz2'
    'all2_lz1'
    'all2_lz3'
    'all2_eh1'
    'all2_eh2'
    'all2_cp2'
    'all2_cp1'
    'all2_ml1'
    'all2_ml2'
    'all2_oo1'
    'all2_oo2'
    'all2_mc2'
    'all2_mc1'
    'all2_ht1'
    'all2_can1'
    'all2_wf'
    'all2_ar2'
    'all2_ar1'
    'all2_lr2'
    'all2_cn2'
    'all2_cn1'
    'all2_mg1'
    'all2_mg2'
    'all2_mh2'
    'all2_mh1'
    'all2_de1'
    'all2_de2'
    'all2_fb1'
    'all2_slz1'
    'all2_slz2'
    'all2_hpz'
    'all2_hz2'
    'all2_iz1'
    'all2_iz2'
    'all2_ai1'
    'all2_lb2'
    'all2_lb1'
    'all2_sy1'
    'all2_gh2'
    'all2_sl3'
    'all2_sb1'
    'all2_ml3'
    'all2_ht2'
    'all2_can2'
    'all2_lr1'
    'all2_fb2'
    'all2_hz1'
    'all2_ai2'
)

for i in `seq 0 57`
do
    retro-contest run --agent sonic/dmr-agent:all2 --results-dir ${results[$i]} --no-nv --use-host-data ${Act_name[$i]}
done
